# source /workspace/setup_env.sh

# python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3.1-32B-Instruct/main --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2
# python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3-1125-32B/stage1-step0 --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2
python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3-1125-32B/stage1-step1000 --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2
# python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3-1125-32B/stage1-step50000 --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2
# python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3-1125-32B/stage1-step100000 --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2
# python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3-1125-32B/stage1-step168000 --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2
# python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3-1125-32B/stage1-step337000 --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2
# python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3-1125-32B/stage1-step499000 --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2
# python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3-1125-32B/stage3-step1000 --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2
# python -m analyses.plot_histogram --activations-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/activations/allenai_Olmo-3-1125-32B/main --filtering-dir outputs/transcripts/upgrade/allenai_Olmo-3.1-32B-Instruct/main/filtering/ --minimum-rating 2

